Load_Order:
  File: C:\Users\evild\AppData\Local\Fallout4\loadorder.txt
Mod_Organizer:
  Binary: C:\Modding\MO2\ModOrganizer.exe
  Install_Path: C:\Modding\MO2
xEdit:
  Binary: D:\Programs\xEdit 4.1\xEdit64.exe
  Install_Path: D:\Programs\xEdit 4.1
